default_platform(:ios)

platform :ios do
  desc "Push a new beta build to Testflight"
  lane :deploy_appstore_connect do
  #   match(type: "appstore")  # Sincroniza los certificados y perfiles
  #   build_app(scheme: "Runner")  # Reemplaza "YourAppScheme" con el esquema de tu app
  #   pilot(api_key_path: "fastlane/store.json" , skip_waiting_for_build_processing: true)
  # end
#   lane :beta do 
#     setup_ci if ENV["CI"]

#     # Crear el llavero en el sistema
#     sh("security create-keychain -p tmpKeyChainPass /Users/runner/Library/Keychains/tmpKeyChain.keychain-db")
#     sh("security unlock-keychain -p tmpKeyChainPass /Users/runner/Library/Keychains/tmpKeyChain.keychain-db")
#     sh("security list-keychains -d user -s /Users/runner/Library/Keychains/tmpKeyChain.keychain-db $(security list-keychains -d user | tr -d '\"')")


    match
      app_identifier: "com.schoolcontrol.trudev", 
      type: "appstore", 
      readonly: true, 
    )
    build_app(scheme: "Runner" )
    pilot(api_key_path: "fastlane/store.json" , skip_waiting_for_build_processing: true)
  end
end


