default_platform(:ios)

platform :ios do
  desc "Push a new beta build to Testflight"
  lane :beta do 
    # sync_code_signing(
    #   type: "appstore", # O el tipo que corresponda (appstore, development, etc.)
    #   app_identifier: 'com.schoolcontrol.trudev',
    #   readonly: true
    # )
    xcversion(version: "16.0") # Cambia a la versión que necesitas
    setup_ci if ENV["CI"]
    match(app_identifier:"com.schoolcontrol.trudev", type:"appstore")
    build_app(workspace: "Runner.xcworkspace" , scheme: "Runner")
    pilot(api_key_path: "fastlane/store.json" , skip_waiting_for_build_processing: true)
  end
end
