name: Deploy to TestFlight

on:
    push:
        branches:
            - develop # Configura el branch que desencadenará el despliegue

jobs:
    deploy:
        runs-on: macos-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v3

            - name: Setup Flutter environment
              uses: subosito/flutter-action@v2
              with:
                  channel: "stable"

            - name: Setup Ruby
              uses: ruby/setup-ruby@v1
              with:
                  ruby-version: "3.3"
                  bundler-cache: true

            - name: Install Fastlane
              run: gem install fastlane

            - name: SEt up App Store Connect file
              run: |
                  cd ios
                  cd fastlane
                  echo '${{ secrets.APP_STORE_CONNECT_JSON_KEY }}' > store.json
            - name: Run Fastlane
              working-directory: ios
              run: |
                  bundler exec fastlane ios beta
              env:
                  MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
                  MATCH_GIT_BASIC_AUTHORIZATION: ${{ secrets.MATCH_GIT_BASIC_AUTHORIZATION }}
                  FASTLANE_PASSWORD: ${{ secrets.FASTLANE_PASSWORD }}
                  CI: true
