name: Deploy to TestFlight

on:
    push:
        branches:
            - develop

jobs:
    build:
        runs-on: macos-latest

        steps:
            - name: Check out repository
              uses: actions/checkout@v3

            - name: Set up Match Repo
              env:
                  MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
                  GH_PAT: ${{ secrets.GH_PAT }}
              run: |
                  git clone https://${{ secrets.GH_PAT }}@github.com/rterrones87/Trudev-iOS-Certificates.git
                  cd Trudev-iOS-Certificates
                  git config user.email "github-actions[bot]@users.noreply.github.com"
                  git config user.name "github-actions[bot]"

            - name: Set up Flutter
              uses: subosito/flutter-action@v2
              with:
                  channel: "stable" # Asegura el canal `stable` sin especificar una versión exacta
            - name: Confirm Flutter installation and version
              run: flutter --version

            - name: Install dependencies
              run: flutter pub get

            - name: Set up Ruby
              uses: ruby/setup-ruby@v1
              with:
                  ruby-version: "3.0" # Asegúrate de usar una versión compatible con Fastlane
                  bundler-cache: true

            - name: Install Fastlane
              run: gem install fastlane

            # - name: Configure Environment Variables
            #   env:
            #       APP_STORE_CONNECT_KEY_ID: ${{ secrets.APP_STORE_CONNECT_KEY_ID }}
            #       APP_STORE_CONNECT_ISSUER_ID: ${{ secrets.APP_STORE_CONNECT_ISSUER_ID }}
            #       APP_STORE_CONNECT_KEY_PATH: "./fastlane/AuthKey_XCG96459Y9.p8"
            #       MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
            #   run: |
            #       echo "${{ secrets.APP_STORE_CONNECT_KEY }}" > $APP_STORE_CONNECT_KEY_PATH

            - name: Build and deploy with Fastlane
              env:
                  FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD: ${{ secrets.FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD }}
                  MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
              run: |
                  fastlane deploy_appstore_connect
