name: Deploy to App Store Connect

on:
    pull_request:
        branches:
            - main # Solo se ejecuta en PR dirigidos a `main`

jobs:
    deploy:
        runs-on: macos-latest

        steps:
            - name: Check out the repository
              uses: actions/checkout@v2

            - name: Set up Ruby
              uses: ruby/setup-ruby@v1
              with:
                  ruby-version: 3.0 # Asegúrate de usar la misma versión de Ruby que en tu entorno local

            - name: Install Bundler
              run: gem install bundler

            - name: Set up Flutter
              uses: subosito/flutter-action@v2
              with:
                  flutter-version: "3.5.3" # Especifica la versión correcta de Flutter

            - name: Switch to stable channel
              run: flutter channel stable && flutter upgrade

            - name: Install Fastlane
              run: bundle install
              working-directory: ios

            - name: Build and deploy to App Store Connect
              working-directory: ios # Cambia al directorio `ios`
              env:
                  APP_STORE_KEY_ID: ${{ secrets.APP_STORE_KEY_ID }}
                  APP_STORE_ISSUER_ID: ${{ secrets.APP_STORE_ISSUER_ID }}
                  APP_STORE_KEY_PATH: ${{ secrets.APP_STORE_KEY_PATH }}
                  FASTLANE_USER: ${{ secrets.FASTLANE_USER }}
                  FASTLANE_PASSWORD: ${{ secrets.FASTLANE_PASSWORD }}
              run: fastlane deploy_appstore_connect
