name: Deploy to TestFlight

on:
    push:
        branches:
            - develop # Configura el branch que desencadenará el despliegue

jobs:
    deploy:
        runs-on: macos-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v2

            - name: Set up Ruby
              uses: ruby/setup-ruby@v1
              with:
                  ruby-version: "3.0" # Especifica la versión de Ruby que necesitas

            - name: Install Fastlane
              run: gem install fastlane

            - name: Setup Flutter
              uses: subosito/flutter-action@v2
              with:
                  flutter-version: "3.3.0" # Ajusta según la versión de Flutter que usas

            - name: Build Flutter for iOS
              run: flutter build ios --release --no-codesign

            - name: Setup Fastlane Match
              env:
                  MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }} # Agrega la contraseña de match en GitHub Secrets
              run: |
                  cd ios
                  fastlane match appstore --readonly

            - name: Deploy to TestFlight
              env:
                  APP_STORE_CONNECT_API_KEY_ID: ${{ secrets.APP_STORE_CONNECT_API_KEY_ID }}
                  APP_STORE_CONNECT_API_ISSUER_ID: ${{ secrets.APP_STORE_CONNECT_API_ISSUER_ID }}
                  APP_STORE_CONNECT_API_KEY: ${{ secrets.APP_STORE_CONNECT_API_KEY }}
                  GH_PAT: ${{ secrets.GH_PAT }} # Contenido del archivo `.p8`
              run: |
                  cd ios
                  bundle exec fastlane deploy_appstore_connect
